# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and lint
permissions:
  contents: read

on:
  push:
    branches: ["main", "v[0-9]+.[0-9]+.x", "v[0-9]+.x"]
  pull_request:
    branches: ["main", "v[0-9]+.[0-9]+.x", "v[0-9]+.x"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - name: Run linting
        run: npm run lint

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - name: Run type-checking
        run: npm run check
